{{- if ne .Values.keys.type "existing-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ics-operator.fullname" . }}-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ics-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: keys
type: Opaque
stringData:
  {{- if eq .Values.keys.type "mnemonic" }}
  mnemonic: {{ .Values.keys.mnemonic | quote }}
  hd-path: {{ include "ics-operator.hdPath" . | quote }}
  {{- if .Values.devnet.enabled }}
  # For devnet with known mnemonic, we can provide the address
  address: {{ include "ics-operator.getAddress" . | quote }}
  {{- end }}
  {{- else if eq .Values.keys.type "explicit" }}
  priv_validator_key.json: |
{{ .Values.keys.validatorKey | indent 4 }}
  node_key.json: |
{{ .Values.keys.nodeKey | indent 4 }}
  {{- end }}
{{- end }}