kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: bob-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30656
    hostPort: 26666
    protocol: TCP
  - containerPort: 30657
    hostPort: 26658
    protocol: TCP
  - containerPort: 31657
    hostPort: 1318
    protocol: TCP
  - containerPort: 32090
    hostPort: 9092
    protocol: TCP
  - containerPort: 32091
    hostPort: 9093
    protocol: TCP
networking:
  podSubnet: "10.245.0.0/16"
  serviceSubnet: "10.97.0.0/12"